<a href="https://colab.research.google.com/github/aneuraz/intro-keras/blob/master/LSTM_classification_student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification de texte en deep learning (LSTM et convolution) 

## But de la tâche 

A partir d'un dataset d'articles PUBMED, le but est de classifier les articles dans des catégories thématiques en fonction de leur titre. 

Après une phase de préprocessing du texte, nous entrainerons un modèle à base de convolutions, puis un modèle à base de réseau de neurones récurrents (LSTM) 

## Cloner le repo https://github.com/aneuraz/intro-keras.git

In [ ]:
!git clone https://github.com/aneuraz/intro-keras.git

## Import des libraries

In [ ]:
%tensorflow_version 2.x
import json 
import tensorflow as tf
import numpy as np

## Chargement des données

Toutes les données chargées se situent dans le répertoire `/content/`.
Les données sont dans un fichier JSON.

In [ ]:
with open('/content/intro-keras/ai_pub_samp.json','r') as f:
  data = json.load(f)

In [ ]:
data[0]

{'Cat_2013': 'C',
 'Cat_2014': 'C',
 'Cat_2015': 'C',
 'Cat_2016': 'C',
 'Cat_2017': 'B',
 'Disciplines': ['XQ'],
 'ESSN': '1873-3557',
 'IF_2013': '2.129',
 'IF_2014': '2.353',
 'IF_2015': '2.653',
 'IF_2016': '2.536',
 'IF_2017': '2.88',
 'ISSN': '1386-1425',
 'ISSN_online': '1873-3557',
 'ISSN_print': '1386-1425',
 'IsoAbbr': 'Spectrochim Acta A Mol Biomol Spectrosc',
 'JrId': 20555,
 'MedAbbr': 'Spectrochim Acta A Mol Biomol Spectrosc',
 'NLMid': '9602533',
 'Titre': 'Spectrochim Acta A Mol Biomol Spectrosc',
 'abstract': 'In this research, ZnO nanoparticle loaded on activated carbon (ZnO-NPs-AC) was synthesized simply by a low cost and nontoxic procedure. The characterization and identification have been completed by different techniques such as SEM and XRD analysis. A three layer artificial neural network (ANN) model is applicable for accurate prediction of dye removal percentage from aqueous solution by ZnO-NRs-AC following conduction of 270 experimental data. The network was tr

## TODO: Extraire les titres et les catégories

In [ ]:
# mettre le titre en minuscule dans la variable X


# mettre la catégorie (1e élément de la liste) dans la variable Y


## TODO: Calculer la longueur maximale des titres dans le dataset

In [ ]:
# longueur maximale des titres, variable max_len


## TODO: Diviser le dataset en train (X_train, Y_train) et test (X_test, Y_test)

In [ ]:
# X_train, Y_train


# X_test, Y_test


## Transformer la variable Y en vecteur numerique

["Cat 1", "Cat 2"] -> [0, 1]

In [ ]:
# creer un mapping cat_2_id

# creer un reverse mapping id_2_cat

# calculer la taille du vocabulaire cat_vocab




In [ ]:
# preprocesser les X_train et X_test en X_train_id et X_test_id


## Tokenizer les titres

Pour cela vous pouvez utiliser la fonction `Tokenizer` de keras

Le but est de transformer les textes en un vecteur numérique

texte -> liste de tokens -> vecteur numérique

"Miaou le chat" -> ["Miaou", "le", chat"] -> [1, 2, 3]

In [ ]:
# Créer le tokenizer



In [ ]:
# Entrainer le tokenizer sur le train set 


In [ ]:
# Transformer les textes en vecteurs numeriques à l'aide du tokenizer


## Faire un padding des sequences obtenues pour qu'elles aient toutes la même taille (cf la fonction `pad_sequences`)

[1, 2, 3]       -> [0, 0, 1, 2 ,3]

[4, 5, 6, 7, 8] -> [4, 5, 6, 7, 8]

In [ ]:
# Padding des sequences 


In [ ]:
X_train_seq[0:5]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,   21,    9,   16,  945,   48,    4,
          79,    1, 5677, 1973, 2247, 2614,    7, 2248, 2615, 5678, 3995,
          13, 1586,  946, 1974,    2, 5679,   37],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,  462,    1,   74,  124,   48,    3,
         615,  616, 3135,   10,    5,  693,   48],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,  135,   14,    1,  589,
         143,  327,    3, 3136, 1337,   64, 2616],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,  

In [ ]:
X_test_seq[0:5]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,   23,   18, 3459,
        9708,  197,  117,    3,    6,   85, 1354],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,   72,   89,    3,  911,  818,    3,    5, 1288,
           1,  116,   14,    1,  255, 9110,  412],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,   46,   18,   23,
         262,  142, 1309,    3,   19,  823,   33],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,  368,    2,  561,  

In [ ]:
Y_test_id[0:100]

array([30, 30, 11,  6,  6,  6,  7, 22, 22, 45, 22, 11, 21, 44,  7, 15, 56,
        3,  8,  3, 13, 70, 11, 56, 11, 30, 11, 44, 31, 15, 79, 11,  6, 11,
        4, 13,  6, 65, 49, 56, 12,  6,  6,  6,  6, 22, 86, 26, 11,  3, 12,
       19, 11,  6, 21, 56,  7,  6, 11,  2, 46,  7,  3, 21, 13,  9,  3,  6,
       19, 49,  2, 11, 27, 13, 71, 59, 13,  6, 13, 15,  3,  6,  6, 11, 22,
        6, 13, 28,  8, 22,  6, 11,  6, 21,  6, 50, 46, 14, 17, 21])

# Réseau de convolution pour la classification de texte

Les réseaux convolutionnels peuvent également être utiliser pour le texte et notamment pour la classification de texte. Ici nous allons construire un CNN sur le même modèle que pour les images avec quelques petites spécificités. 

Comme le texte est une séquence de mots, il s'agit d'une séquence en 1 dimension. Nous appliquerons donc une convolution en 1D. 

Pour traiter du texte, la première couche de notre réseau va être constituée par une couche d'embedding. 

Pour rappel, le word embedding consiste à projeter les tokens dans un espace vectoriel qui va minimiser la distance entre les tokens qui sont utilisés dans des contextes similaires (et qui ont un sens proche ? )

![Texte alternatif…](https://www.ibm.com/blogs/research/wp-content/uploads/2018/10/WMEFig1.png)

Les embeddings peuvent être calculés de diverses façons. Par exemple word2vec, un des plus célèbres, se base sur 2 algorithmes frères Skip-gram et CBOW

![Texte alternatif…](https://pathmind.com/images/wiki/word2vec_diagrams.png)

Pour information, il existe aujourd'hui des algorithmes plus performants que word2vec comme [Fasttext](https://fasttext.cc) qui prend en compte des informations de sous-mots ou la famille des embeddings contextuels comme [ELMo](https://allennlp.org/elmo) ou [BERT](https://arxiv.org/abs/1810.04805) qui prennent en compte le contexte d'utilisation du mot pour calculer son vecteur. 

In [ ]:
# Créer le modèle avec au minimum
# Embedding 
# Dropout
# Convolution
# Maxpooling
# Dense
# Activation
# Classifieur (Dense + activation softmax)


# Compiler le modèle 

# Afficher le summary du modèle


In [ ]:
# Fitter le modèle 


In [ ]:
# Evaluer le modèle


# LSTM pour la classification de texte

Il est également possible d'utiliser un autre type de réseau de neurones pour effectuer ce genre de tâches: les réseaux de neurones récurrents ou RNN.

Les RNN sont conçus pour gérer les séquences. Le réseau prend les tokens un par un et calcule une représentation de la séquence à chaque pas qui tiens compte de tous les pas précédents 

![Texte alternatif…](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Recurrent_neural_network_unfold.svg/450px-Recurrent_neural_network_unfold.svg.png)


Il existe différents types de RNN. Ici nous utiliserons les Long Short-Term Memory (LSTM) qui permettent d'améliorer les performances sur des séquences longues avec une série de "gates". 

![Texte alternatif…](http://dprogrammer.org/wp-content/uploads/2019/04/RNN-vs-LSTM-vs-GRU-1200x361.png)

In [ ]:
# Créer un réseau à base de LSTM avec au minimum:
# Embedding
# Dropout
# LSTM
# Dropout
# Classifieur


# Compiler le modèle 

# Afficher le summary du modèle


In [ ]:
# Fitter le modèle


In [ ]:
# Evaluer le modèle
